service:
  name: "NotificationService"
  environment: "development"
  port: 3000

templates:
  path: "./templates/"
  default_language: "en"

providers:
  mailgun:
    api_key: "foo"
    domain: "bar"
